// ============================================================
// NEW PROMPTS - DRAFTED FROM COMPETITOR GAP ANALYSIS
// Inspired by godofprompt.ai gaps, 100% original content
// Add these to prompts.js before the closing ];
// ============================================================

// ==================== IMAGE GENERATION ====================

  {
    "title": "Product Photography Prompt Generator",
    "description": "Describe your product and get a detailed AI image generation prompt for stunning product shots ready for Midjourney, DALL-E, or Stable Diffusion.",
    "method": "Copy and paste this prompt into ChatGPT, Claude, or Gemini. Then paste the output into your AI image generator of choice.",
    "prompt": "You are an expert commercial photographer and AI image prompt engineer who has directed product shoots for Fortune 500 brands.\n\nMy product: [PRODUCT NAME AND DESCRIPTION]\nBrand style: [MINIMAL/LUXURY/PLAYFUL/BOLD/ORGANIC]\nPlatform: [INSTAGRAM/WEBSITE HERO/AMAZON LISTING/PRINT AD]\n\nGenerate 5 highly detailed AI image generation prompts for this product. Each prompt must include:\n\n1. **Camera & Lens Spec** - specific camera model, focal length, aperture (e.g., Sony A7IV, 85mm f/1.4)\n2. **Lighting Setup** - key light, fill light, rim light, color temperature, modifiers\n3. **Background & Surface** - material, color, texture, props\n4. **Composition** - rule of thirds placement, angle (flat lay, 45-degree, eye-level, hero angle)\n5. **Post-Processing Style** - color grading, contrast, shadows, highlights\n6. **Mood Keywords** - 5-8 descriptive words that define the aesthetic\n\nVariations to cover:\n- Clean white/studio shot (for e-commerce)\n- Lifestyle/in-context shot (product in use)\n- Dramatic/moody hero shot (for ads)\n- Flat lay with props (for social media)\n- Close-up detail/texture shot (for premium feel)\n\nFormat each prompt as a single paragraph ready to paste into Midjourney or DALL-E. Add negative prompt suggestions for each.",
    "category": "Image Generation"
  },
  {
    "title": "AI Portrait Photography Director",
    "description": "Get cinematic portrait prompts with precise lighting, mood, and styling instructions for AI image generators.",
    "method": "Paste into any LLM. Replace the placeholders with your vision, then use the output in Midjourney, DALL-E, or Stable Diffusion.",
    "prompt": "You are a world-renowned portrait photographer who has shot covers for Vogue, GQ, and National Geographic. You also specialize in crafting AI image generation prompts.\n\nSubject: [DESCRIBE THE PERSON - age, style, vibe]\nMood: [CINEMATIC/EDITORIAL/CANDID/DRAMATIC/DREAMY/GRITTY]\nSetting: [STUDIO/URBAN/NATURE/INTERIOR/ABSTRACT BACKGROUND]\nPurpose: [SOCIAL MEDIA AVATAR/BRAND CAMPAIGN/ARTISTIC PROJECT/HEADSHOT]\n\nCreate 6 detailed AI portrait prompts covering these styles:\n\n1. **Classic Studio Portrait** - Rembrandt lighting, clean backdrop, sharp focus on eyes\n2. **Cinematic Street Portrait** - Golden hour, bokeh background, film grain aesthetic\n3. **Editorial Fashion** - High contrast, dramatic shadows, magazine-cover composition\n4. **Candid Lifestyle** - Natural light, authentic expression, environmental context\n5. **Dramatic Low-Key** - Single hard light source, deep shadows, moody atmosphere\n6. **Dreamy/Ethereal** - Soft diffused light, pastel tones, shallow depth of field\n\nFor each prompt specify: exact camera settings, lens choice, lighting diagram, color palette (hex codes), post-processing instructions, and 8-10 style keywords.\n\nFormat as copy-paste ready prompts. Include aspect ratio recommendations for each use case.",
    "category": "Image Generation"
  },
  {
    "title": "Food Photography Prompt Crafter",
    "description": "Describe any dish or food product and get mouthwatering AI image prompts with professional styling, lighting, and plating directions.",
    "method": "Paste into your preferred LLM. Replace [DISH] with your food item. Use the generated prompts in any AI image tool.",
    "prompt": "You are a professional food photographer and stylist who has shot for Bon Appetit, Food & Wine, and major restaurant brands.\n\nDish/Food: [DISH OR FOOD PRODUCT]\nBrand vibe: [RUSTIC/MODERN/LUXURY/HOMESTYLE/HEALTH-FOCUSED]\nUse case: [MENU/INSTAGRAM/PACKAGING/COOKBOOK/ADVERTISEMENT]\n\nCreate 5 professional food photography prompts:\n\n1. **Overhead Flat Lay** - Top-down shot with complementary ingredients scattered artfully, linen textures, natural light from window\n2. **Hero Angle (45-degree)** - Main dish front-center, shallow depth of field, steam/movement captured\n3. **Close-Up Texture Shot** - Macro detail showing texture, moisture, freshness cues\n4. **Lifestyle Scene** - Hands reaching, mid-bite moment, table setting with drinks and sides\n5. **Dark & Moody** - Dark wood surface, dramatic side lighting, chiaroscuro style\n\nFor each prompt include:\n- Exact prop styling (utensils, napkins, garnishes, surfaces)\n- Lighting setup (natural vs artificial, direction, diffusion)\n- Color palette that makes the food pop\n- Composition technique (leading lines, negative space, rule of odds)\n- Camera settings (macro lens, aperture, white balance)\n- 10 descriptive keywords for AI generation\n\nMake each prompt a single paragraph ready for Midjourney. Include tips on what to avoid (common AI food photography mistakes).",
    "category": "Image Generation"
  },
  {
    "title": "Logo and Brand Mark Generator",
    "description": "Input your brand name and values to get detailed AI prompts for generating professional logos, icons, and brand marks.",
    "method": "Paste into any LLM with your brand details filled in. Use the output prompts in Midjourney, DALL-E, or Ideogram.",
    "prompt": "You are a senior brand identity designer with 20 years of experience creating logos for startups and global brands alike.\n\nBrand name: [BRAND NAME]\nIndustry: [INDUSTRY]\nBrand values: [3-5 CORE VALUES]\nStyle preference: [WORDMARK/ICON/COMBINATION/EMBLEM/ABSTRACT]\nColor preference: [COLORS OR 'SUGGEST FOR ME']\n\nGenerate 8 distinct AI image prompts for logo concepts:\n\n1. **Minimal Wordmark** - Clean typography, modern sans-serif, no icon\n2. **Icon + Wordmark** - Simple geometric icon paired with type\n3. **Abstract Symbol** - Unique abstract mark that captures brand essence\n4. **Lettermark/Monogram** - Initials designed as a unified mark\n5. **Emblem Style** - Badge or crest format, premium feel\n6. **Negative Space Concept** - Clever use of hidden shapes within letters\n7. **Geometric Minimalist** - Based on circles, squares, golden ratio\n8. **Hand-Drawn/Organic** - Artisan, human-touch feel\n\nFor each prompt specify:\n- Exact style descriptors (flat design, 3D, gradient, line art)\n- Background (white, dark, transparent)\n- Typography style if applicable\n- Mandatory keywords: vector, scalable, professional, high contrast\n- Negative prompts: avoid photorealistic, avoid complex details, avoid text errors\n\nAlso provide guidance on which logo style works best for: app icons, business cards, social media avatars, and large signage.",
    "category": "Image Generation"
  },
  {
    "title": "Social Media Visual Content System",
    "description": "Get a complete visual content system with AI image prompts for Instagram carousels, story templates, post graphics, and cover images.",
    "method": "Fill in your brand details and paste into any LLM. Use outputs in Canva, Midjourney, or DALL-E.",
    "prompt": "You are a creative director who specializes in visual social media strategies for brands with millions of followers.\n\nBrand: [BRAND NAME]\nIndustry: [INDUSTRY]\nTarget audience: [WHO THEY ARE]\nBrand colors: [PRIMARY AND SECONDARY COLORS]\nContent pillars: [3-4 CONTENT THEMES]\n\nCreate a complete visual content system with AI image prompts for:\n\n**Instagram Feed Posts (5 prompts)**\n- Quote graphic with branded background\n- Product/service showcase\n- Behind-the-scenes style\n- Data/statistic visual\n- User-generated content style recreation\n\n**Instagram Stories (3 prompts)**\n- Poll/question background template\n- Announcement/launch visual\n- Testimonial highlight card\n\n**LinkedIn Posts (3 prompts)**\n- Professional thought leadership graphic\n- Infographic-style data visual\n- Team/culture photo style\n\n**YouTube/TikTok Thumbnails (3 prompts)**\n- High-contrast face + text overlay style\n- Before/after comparison\n- Curiosity-gap visual\n\nFor each prompt specify: exact dimensions, color codes, typography style, visual hierarchy, and mood. Format as ready-to-use AI generation prompts. Include a visual brand consistency checklist.",
    "category": "Image Generation"
  },
  {
    "title": "Real Estate Listing Photo Enhancer",
    "description": "Upload property details and get AI prompts for virtual staging, twilight shots, aerial views, and lifestyle photography for real estate listings.",
    "method": "Paste into your preferred LLM with property details. Use the generated prompts in AI image tools for virtual staging.",
    "prompt": "You are a top real estate photographer and virtual staging expert who has photographed luxury properties for Sotheby's and Christie's.\n\nProperty type: [HOUSE/CONDO/APARTMENT/COMMERCIAL]\nStyle: [MODERN/TRADITIONAL/FARMHOUSE/INDUSTRIAL/COASTAL]\nKey rooms: [LIST THE ROOMS TO PHOTOGRAPH]\nTarget buyer: [FIRST-TIME BUYER/LUXURY/INVESTOR/FAMILY]\nPrice range: [PRICE BRACKET]\n\nGenerate detailed AI image prompts for:\n\n1. **Virtual Staging** - For each room listed, create a prompt that adds furniture, decor, and styling appropriate to the property's style and target buyer. Specify exact furniture pieces, rug styles, art, plants, and lighting fixtures.\n\n2. **Twilight Exterior** - Golden hour/blue hour exterior shot with warm interior lights glowing, landscaping enhanced, sky replacement if needed.\n\n3. **Aerial/Drone View** - Bird's eye establishing shot showing property, yard, neighborhood context.\n\n4. **Lifestyle Vignette** - Scene that helps buyers imagine living there (morning coffee on the patio, family dinner, reading by fireplace).\n\n5. **Before/After Enhancement** - Take a plain room description and create prompts for both the empty version and the staged version.\n\nFor each prompt include: camera angle, lighting (natural vs enhanced), color temperature (warm and inviting), composition rules, and specific prop/furniture brands or styles to reference. Format for Midjourney with aspect ratios for MLS listings (3:2) and social media (4:5).",
    "category": "Image Generation"
  },
  {
    "title": "AI Art Style Transfer Prompt Builder",
    "description": "Describe any subject and choose an art style to get detailed prompts that recreate famous artistic styles in AI image generators.",
    "method": "Paste into any LLM. Pick your subject and style. Use the output in Midjourney, Stable Diffusion, or DALL-E.",
    "prompt": "You are an art historian and AI prompt engineer who understands the technical characteristics of every major art movement and style.\n\nSubject: [WHAT YOU WANT TO DEPICT]\nPreferred style: [CHOOSE OR SAY 'GIVE ME OPTIONS']\n\nCreate 10 AI image prompts, each in a different iconic art style:\n\n1. **Impressionist** (Monet-inspired) - soft brushstrokes, light play, pastel palette\n2. **Pop Art** (Warhol-inspired) - bold colors, halftone dots, graphic contrast\n3. **Art Nouveau** - flowing organic lines, floral motifs, decorative borders\n4. **Cyberpunk/Neon** - neon lights, rain-slicked streets, futuristic dystopia\n5. **Japanese Ukiyo-e** - woodblock print style, flat color, wave patterns\n6. **Surrealism** (Dali-inspired) - dreamlike, melting forms, impossible physics\n7. **Minimalist/Bauhaus** - geometric shapes, primary colors, clean lines\n8. **Dark Fantasy** - dramatic lighting, gothic architecture, rich textures\n9. **Watercolor Illustration** - soft washes, visible paper texture, gentle bleeds\n10. **Pixel Art/Retro Gaming** - 8-bit or 16-bit style, limited palette, nostalgic\n\nFor each prompt include:\n- Art movement context (what defines this style technically)\n- 10-15 specific style keywords for AI generators\n- Color palette (5 hex codes per style)\n- Composition approach specific to that art movement\n- Recommended AI model and settings\n- Negative prompts to avoid common AI artifacts in that style",
    "category": "Image Generation"
  },
  {
    "title": "Midjourney Prompt Formula Master",
    "description": "Learn the exact formula for writing Midjourney prompts. Get templates, parameter cheat sheets, and 10 ready-to-use prompts for any subject.",
    "method": "Paste into any LLM. Describe what you want to create and get back structured Midjourney prompts with all the right parameters.",
    "prompt": "You are the world's leading Midjourney prompt engineer. You've generated thousands of images and understand exactly how Midjourney interprets language, parameters, and style references.\n\nWhat I want to create: [DESCRIBE YOUR VISION]\nStyle: [PHOTOREALISTIC/ILLUSTRATION/3D RENDER/ABSTRACT/ANIME]\nMood: [DESCRIBE THE FEELING]\n\nFirst, teach me your Midjourney prompt formula:\n\n1. **The Formula** - Break down the exact structure: [Subject] + [Medium] + [Style] + [Lighting] + [Color] + [Composition] + [Quality boosters] + [Parameters]\n\n2. **Parameter Cheat Sheet** - Explain every useful parameter: --ar, --s, --c, --q, --v, --style, --no, --seed, --tile, --weird. When to use each one and at what values.\n\n3. **Quality Boosters** - List the 20 most powerful keywords that improve output quality (e.g., 'octane render', '8k', 'masterpiece', 'award-winning', etc.) and explain when each works best.\n\n4. **Word Order Matters** - Explain how Midjourney weights words by position and how to use :: for custom weighting.\n\n5. **10 Ready-to-Use Prompts** - Generate 10 complete Midjourney prompts for my subject, each with a different style/approach. Include all parameters. Make them copy-paste ready.\n\n6. **Common Mistakes** - List the top 10 mistakes that produce bad Midjourney results and how to fix each one.\n\nBe specific, technical, and actionable. No fluff.",
    "category": "Image Generation"
  },

// ==================== UI/UX & WEB DESIGN ====================

  {
    "title": "Landing Page Conversion Architect",
    "description": "Describe your product and audience to get a complete high-converting landing page structure with copy, layout, and CTA strategy.",
    "method": "Paste into any LLM with your product details. Get back a full landing page blueprint you can hand to a designer or build yourself.",
    "prompt": "You are a conversion rate optimization expert who has designed landing pages that generated over $100M in revenue. You combine direct-response copywriting with modern UX psychology.\n\nProduct/Service: [WHAT YOU'RE SELLING]\nTarget audience: [WHO THEY ARE AND THEIR BIGGEST PAIN POINT]\nPrice point: [PRICE OR PRICING MODEL]\nGoal: [SIGN UP/BUY/BOOK A CALL/DOWNLOAD]\nCurrent conversion rate: [IF KNOWN, OR 'NEW PAGE']\n\nDesign a complete landing page blueprint:\n\n**1. Above the Fold (Hero Section)**\n- Headline formula (Problem-Agitate-Solution)\n- Write 3 headline variations to A/B test\n- Subheadline that adds specificity\n- Primary CTA button (exact text, color psychology reasoning)\n- Hero image/video direction\n- Social proof element (what type and where)\n\n**2. Problem Section**\n- 3 pain points that make visitors feel understood\n- Agitation copy that raises the stakes\n- Emotional trigger words specific to this audience\n\n**3. Solution Section**\n- How your product solves each pain point\n- Feature-to-benefit translation table\n- Visual layout recommendation (icons, screenshots, demo)\n\n**4. Social Proof Stack**\n- Testimonial placement strategy (which types, how many)\n- Trust badge recommendations\n- Numbers/stats to display\n- Logo bar if B2B\n\n**5. Objection Handling**\n- Top 5 objections this audience will have\n- FAQ copy that neutralizes each\n- Risk reversal (guarantee copy)\n\n**6. Final CTA Section**\n- Urgency/scarcity element (ethical, not fake)\n- Final push copy\n- Secondary CTA for not-ready visitors\n\n**7. Technical Specs**\n- Page load optimization priorities\n- Mobile-first layout rules\n- Tracking setup (what to measure)\n\nWrite all copy in the brand's voice. Make it specific, not generic.",
    "category": "UI/UX Design"
  },
  {
    "title": "Mobile App UX Audit Prompt",
    "description": "Describe your mobile app's current flow and get a comprehensive UX audit with specific fixes for navigation, onboarding, and retention.",
    "method": "Paste this prompt into any LLM with details about your app. Share screenshots or describe screens for more specific feedback.",
    "prompt": "You are a senior UX researcher and mobile app designer who has led product design at top consumer apps with 10M+ users.\n\nApp name: [APP NAME]\nApp type: [WHAT IT DOES]\nPlatform: [iOS/ANDROID/BOTH]\nCurrent screens/flow: [DESCRIBE THE MAIN USER JOURNEY OR LIST KEY SCREENS]\nBiggest issue: [WHERE USERS DROP OFF OR COMPLAIN]\n\nConduct a comprehensive UX audit:\n\n**1. First Impression Audit (0-30 seconds)**\n- App store listing optimization (icon, screenshots, description)\n- First open experience critique\n- Value proposition clarity score (1-10 with reasoning)\n\n**2. Onboarding Flow Analysis**\n- Current onboarding friction points\n- Recommended onboarding pattern (progressive, benefits-first, or action-first)\n- Exact screens and copy for ideal onboarding (max 3-4 steps)\n- When to ask for permissions (notifications, location, etc.)\n\n**3. Navigation Architecture**\n- Tab bar / navigation structure recommendation\n- Information architecture review\n- Thumb-zone optimization for key actions\n- Gesture patterns to implement\n\n**4. Core Loop Optimization**\n- Identify the core action users must repeat\n- Friction audit for that action (count taps, time to complete)\n- Simplification recommendations\n- Habit-forming triggers (Hook Model analysis)\n\n**5. Visual Design Review**\n- Typography hierarchy issues\n- Color contrast and accessibility (WCAG compliance)\n- Spacing and padding consistency\n- Component library recommendations\n\n**6. Retention Mechanics**\n- Push notification strategy (timing, content, frequency)\n- Re-engagement triggers\n- Empty state designs\n- Progress indicators and streaks\n\n**7. Priority Fix List**\n- Rank all issues by impact vs effort\n- Top 5 quick wins\n- Top 3 strategic improvements\n- Metrics to track for each change\n\nBe brutally honest. Point out what's broken, not what's nice.",
    "category": "UI/UX Design"
  },
  {
    "title": "SaaS Dashboard Design Blueprint",
    "description": "Get a complete dashboard design system with layout, data visualization strategy, and component specifications for your SaaS product.",
    "method": "Paste into any LLM. Describe your SaaS product and the data users need to see. Get back a full dashboard design spec.",
    "prompt": "You are a product designer who specializes in data-heavy SaaS dashboards. You've designed analytics interfaces for products used by thousands of businesses.\n\nSaaS product: [PRODUCT NAME AND WHAT IT DOES]\nPrimary user: [ROLE - e.g., Marketing Manager, CEO, Developer]\nKey metrics they care about: [LIST 5-10 METRICS]\nData update frequency: [REAL-TIME/HOURLY/DAILY]\nCurrent pain point: [WHAT'S WRONG WITH EXISTING DASHBOARD OR 'BUILDING FROM SCRATCH']\n\nDesign a complete dashboard blueprint:\n\n**1. Information Hierarchy**\n- Which metrics get top-level placement (KPI cards)\n- Which metrics go in charts vs tables\n- What gets a dedicated page vs summary view\n- Progressive disclosure strategy (overview > drill-down)\n\n**2. Layout Architecture**\n- Grid system (12-column, recommended breakpoints)\n- Sidebar navigation structure\n- Header with global actions\n- Widget/card layout with exact sizing ratios\n- Responsive behavior (desktop > tablet > mobile)\n\n**3. Data Visualization Strategy**\n- For each metric, recommend the best chart type (and why)\n- Color system for data (status colors, comparison colors, sequential palettes)\n- Chart interaction patterns (hover, click, drill-down)\n- Empty states and loading states for each widget\n\n**4. Component Specifications**\n- KPI card design (metric, trend indicator, comparison period, spark line)\n- Filter bar (date range, segments, search)\n- Data table (sorting, pagination, bulk actions, export)\n- Alert/notification system for threshold breaches\n\n**5. Customization & Power Features**\n- Drag-and-drop widget arrangement\n- Custom date range comparisons\n- Saved views / report templates\n- Export options (PDF, CSV, scheduled emails)\n\n**6. Design System Tokens**\n- Typography scale (font, sizes, weights)\n- Spacing scale\n- Border radius, shadow levels\n- Color palette with semantic meaning\n\nProvide a wireframe description for the main dashboard view that a designer could build from immediately.",
    "category": "UI/UX Design"
  },
  {
    "title": "Website Redesign Creative Brief Generator",
    "description": "Answer a few questions about your business and get a complete creative brief for a website redesign that any designer or agency can execute.",
    "method": "Fill in the placeholders and paste into any LLM. Share the output with your designer, developer, or agency.",
    "prompt": "You are a creative director at a top digital agency. You've written briefs for hundreds of successful website redesigns.\n\nBusiness: [BUSINESS NAME AND WHAT YOU DO]\nCurrent website URL: [URL OR 'NO EXISTING SITE']\nTarget audience: [PRIMARY AND SECONDARY AUDIENCES]\nTop 3 goals for the new site: [e.g., GENERATE LEADS, SHOWCASE PORTFOLIO, SELL PRODUCTS]\nBrands you admire (design-wise): [2-3 REFERENCE WEBSITES]\nBudget range: [RANGE OR 'FLEXIBLE']\n\nGenerate a comprehensive creative brief:\n\n**1. Project Overview**\n- Business context and why the redesign is needed\n- Success criteria (specific, measurable outcomes)\n- Project scope (pages, features, integrations)\n\n**2. Brand Positioning**\n- Brand personality (5 adjective pairs: e.g., 'Modern but warm, Bold but approachable')\n- Tone of voice guidelines with copy examples\n- Visual identity direction (mood board description)\n\n**3. Sitemap & Information Architecture**\n- Recommended page structure (hierarchy diagram)\n- Primary and secondary navigation\n- User journey maps for each audience segment\n- Content requirements per page\n\n**4. Design Direction**\n- Color palette recommendation (with hex codes and rationale)\n- Typography pairing (heading + body font suggestions)\n- Photography/illustration style\n- Iconography style\n- White space and density preferences\n\n**5. Functional Requirements**\n- Must-have features list (prioritized)\n- Form types and fields\n- Third-party integrations\n- CMS requirements\n- Performance targets (load time, Core Web Vitals)\n\n**6. SEO & Technical Requirements**\n- URL structure\n- Meta data strategy\n- Schema markup needs\n- Redirect mapping from old site\n- Analytics setup\n\n**7. Content Strategy**\n- Pages that need new copy\n- Content migration plan from old site\n- Blog/resource strategy\n- CTA strategy per page\n\n**8. Timeline & Milestones**\n- Phase breakdown (Discovery, Design, Development, Launch)\n- Key deliverables per phase\n- Stakeholder review points\n\nMake this brief specific enough that a designer could start wireframing immediately.",
    "category": "UI/UX Design"
  },
  {
    "title": "E-Commerce Product Page Optimizer",
    "description": "Paste your product details and get a complete product page layout with persuasion elements, trust signals, and conversion-boosting copy.",
    "method": "Fill in product details and paste into any LLM. Apply the output to your Shopify, WooCommerce, or custom product pages.",
    "prompt": "You are a conversion-focused e-commerce UX designer who has optimized product pages for stores doing $1M+ per month.\n\nProduct: [PRODUCT NAME AND DESCRIPTION]\nPrice: [PRICE]\nStore platform: [SHOPIFY/WOOCOMMERCE/CUSTOM]\nAverage order value: [AOV OR ESTIMATE]\nReturn rate concern: [HIGH/LOW/MEDIUM]\n\nDesign the perfect product page:\n\n**1. Image Gallery Strategy**\n- Number of images needed and what each should show\n- Image order (which first, second, third and why)\n- Video placement and content recommendation\n- 360-degree view or zoom capability recommendation\n- User-submitted photo section\n\n**2. Above-the-Fold Layout**\n- Product title optimization (SEO + conversion)\n- Price display strategy (anchoring, strikethrough, savings %)\n- Star rating and review count placement\n- Variant selector UX (size, color - swatches vs dropdowns)\n- Add-to-cart button (size, color, sticky behavior on mobile)\n- Urgency elements (stock levels, shipping cutoff timer)\n\n**3. Product Description Architecture**\n- Benefit-first bullet points (5 max)\n- Expandable detailed description\n- Specifications table\n- Size guide / compatibility info\n- Materials / ingredients with trust language\n\n**4. Trust & Social Proof Stack**\n- Review section layout (summary bar + featured reviews + filters)\n- Trust badges and their exact placement\n- Guarantee/return policy highlight box\n- 'As seen in' or certification logos\n- Real-time purchase notifications (if appropriate)\n\n**5. Cross-Sell & Upsell**\n- 'Complete the look' / 'Frequently bought together' section\n- Bundle offer strategy\n- 'You may also like' algorithm description\n\n**6. Mobile-Specific Optimizations**\n- Sticky add-to-cart bar\n- Swipeable image gallery\n- Accordion sections for details\n- Touch-friendly variant selectors\n\nWrite all copy examples. Make it specific to my product, not generic.",
    "category": "UI/UX Design"
  },
  {
    "title": "Checkout Flow Friction Eliminator",
    "description": "Describe your checkout process and get a step-by-step redesign that reduces cart abandonment and increases completion rates.",
    "method": "Paste into any LLM with your current checkout details. Apply the recommendations to reduce abandonment.",
    "prompt": "You are a checkout optimization specialist. You've reduced cart abandonment rates by 30-50% for dozens of e-commerce brands.\n\nStore platform: [SHOPIFY/WOOCOMMERCE/CUSTOM]\nCurrent checkout steps: [DESCRIBE YOUR CURRENT FLOW]\nCart abandonment rate: [IF KNOWN OR 'UNKNOWN']\nAverage order value: [AOV]\nTop customer complaint: [IF KNOWN]\n\nRedesign my checkout for maximum conversion:\n\n**1. Cart Page Optimization**\n- Cart layout (what to show, what to hide)\n- Order summary clarity\n- Discount code field (where and how to display without hurting margins)\n- Cart abandonment triggers to remove\n- Cross-sell placement (without distracting from checkout)\n\n**2. Checkout Flow Architecture**\n- Single page vs multi-step (recommendation with reasoning)\n- Field reduction audit (which fields to remove, combine, or auto-fill)\n- Guest checkout vs account creation strategy\n- Progress indicator design\n- Form field order optimization\n\n**3. Payment Section**\n- Payment method display order (based on conversion data)\n- Express checkout buttons (Apple Pay, Google Pay, Shop Pay) placement\n- Buy Now Pay Later integration strategy\n- Security badge placement near payment fields\n- Credit card form UX (auto-format, real-time validation)\n\n**4. Shipping Section**\n- Address auto-complete implementation\n- Shipping options display (free shipping threshold, delivery dates)\n- In-store pickup option\n- Tax calculation transparency\n\n**5. Trust Elements**\n- Security messaging (exactly what to say and where)\n- Money-back guarantee placement\n- SSL and payment processor logos\n- Customer service access during checkout\n\n**6. Abandonment Recovery**\n- Exit-intent strategy\n- Abandoned cart email sequence (3 emails with subject lines and copy)\n- SMS recovery message\n- Retargeting ad copy for cart abandoners\n\n**7. Post-Purchase**\n- Order confirmation page optimization (upsell, referral, social share)\n- Confirmation email template\n- Delivery tracking experience\n\nProvide specific copy for all CTAs, error messages, and trust elements.",
    "category": "UI/UX Design"
  },

// ==================== HR & PEOPLE MANAGEMENT ====================

  {
    "title": "Job Description That Actually Attracts Talent",
    "description": "Enter a role title and get a compelling job description that stands out from generic postings and attracts top candidates.",
    "method": "Paste into any LLM with the role details. Use the output on LinkedIn, Indeed, or your careers page.",
    "prompt": "You are a talent acquisition strategist who has written job descriptions that receive 3x more qualified applicants than industry average.\n\nRole: [JOB TITLE]\nCompany: [COMPANY NAME AND WHAT YOU DO]\nTeam size: [HOW MANY PEOPLE ON THE TEAM]\nReports to: [MANAGER TITLE]\nLocation: [REMOTE/HYBRID/ON-SITE + CITY]\nSalary range: [RANGE OR 'COMPETITIVE']\n\nWrite a job description that top candidates actually want to apply to:\n\n**1. Opening Hook (Not a company bio)**\n- Start with what makes this role exciting, not a company paragraph\n- Paint a picture of what their first 90 days look like\n- State the impact they'll have (not just tasks they'll do)\n\n**2. What You'll Actually Do**\n- 5-7 responsibilities written as outcomes, not tasks\n- Distinguish between 'day one' responsibilities and 'year one' goals\n- Show growth trajectory (where this role leads)\n\n**3. What We're Looking For**\n- Must-haves (keep it to 4-5 max, be honest about what's truly required)\n- Nice-to-haves (clearly separated)\n- Traits and mindsets over years of experience\n- Remove bias: no 'rockstar', 'ninja', gendered language, unnecessary degree requirements\n\n**4. What We Offer (Be Specific)**\n- Compensation transparency\n- Benefits that matter (not just 'competitive benefits')\n- Growth and learning opportunities\n- Culture proof points (specific examples, not buzzwords)\n- Unique perks that differentiate\n\n**5. Application Process**\n- Clear, simple steps\n- Expected timeline\n- What to include (and what NOT to waste time on)\n- Accessibility statement\n\n**6. SEO Optimization**\n- Keywords for job board search algorithms\n- Title optimization for LinkedIn/Indeed\n\nTone: confident, specific, human. Zero corporate jargon.",
    "category": "HR & People Management"
  },
  {
    "title": "Interview Scorecard Builder",
    "description": "Define any role and get a structured interview scorecard with behavioral questions, scoring rubrics, and evaluation criteria that reduce bias.",
    "method": "Paste into any LLM. Replace the role details. Use the scorecard for consistent, fair candidate evaluation.",
    "prompt": "You are an industrial-organizational psychologist who designs structured interview processes for high-performance companies.\n\nRole: [JOB TITLE]\nKey competencies needed: [LIST 4-6 COMPETENCIES]\nTeam culture: [DESCRIBE YOUR TEAM'S WORKING STYLE]\nCommon hiring mistakes for this role: [WHAT GOES WRONG]\n\nBuild a complete interview scorecard system:\n\n**1. Competency Framework**\n- For each competency, define:\n  - What 'great' looks like (specific behaviors)\n  - What 'good' looks like\n  - What 'red flag' looks like\n  - How it maps to on-the-job success\n\n**2. Behavioral Interview Questions**\n- 3 questions per competency (12-18 total)\n- Each question should follow STAR format expectations\n- Include follow-up probes for shallow answers\n- Flag questions that test for culture add (not culture fit)\n\n**3. Scoring Rubric**\n- 1-5 scale with specific behavioral anchors at each level\n- Clear definition of what each score means\n- Weighted scoring (which competencies matter most)\n- Overall scoring formula and decision thresholds\n\n**4. Technical Assessment (if applicable)**\n- Take-home vs live assessment recommendation\n- Assessment design principles (realistic, time-bounded, fair)\n- Evaluation criteria for technical work\n\n**5. Bias Mitigation**\n- Pre-interview calibration process\n- Questions to avoid (and why)\n- Halo/horn effect prevention tactics\n- Diversity and inclusion checkpoints\n\n**6. Debrief Template**\n- Individual evaluator notes template\n- Group debrief discussion structure\n- Decision-making framework (when to hire, pass, or re-evaluate)\n- Feedback documentation for rejected candidates\n\nFormat as a printable scorecard that interviewers can use in real-time.",
    "category": "HR & People Management"
  },
  {
    "title": "Employee Onboarding Program Designer",
    "description": "Define a role and company size to get a complete 90-day onboarding plan with day-by-day activities, milestones, and check-in templates.",
    "method": "Fill in your details and paste into any LLM. Customize the output as your onboarding playbook.",
    "prompt": "You are an employee experience designer who has built onboarding programs that achieve 95% new hire retention at 12 months.\n\nRole being onboarded: [JOB TITLE]\nDepartment: [DEPARTMENT]\nCompany size: [STARTUP/SMB/ENTERPRISE]\nRemote/hybrid/on-site: [WORK ARRANGEMENT]\nTeam size: [NUMBER OF PEOPLE ON TEAM]\n\nDesign a complete 90-day onboarding program:\n\n**Pre-Day 1 (Preboarding)**\n- Welcome email sequence (3 emails with exact content)\n- Equipment and access checklist\n- Pre-reading materials\n- Buddy/mentor assignment criteria\n- Manager prep checklist\n\n**Week 1: Orientation & Foundation**\n- Day-by-day schedule (Mon-Fri)\n- Company overview sessions\n- Tool and system setup\n- Team introductions structure\n- First 1:1 with manager (agenda template)\n- 'Quick win' assignment to build confidence\n\n**Weeks 2-4: Learning & Integration**\n- Weekly focus areas\n- Training sessions needed\n- Shadow sessions with key team members\n- First real project (scoped appropriately)\n- Weekly check-in template (questions to ask)\n- Social integration activities\n\n**Weeks 5-8: Building Independence**\n- Increasing responsibility roadmap\n- Cross-functional introductions\n- Feedback collection (from new hire about the process)\n- Mid-point review template (30-day check-in)\n- Goal-setting for remaining onboarding period\n\n**Weeks 9-12: Full Integration**\n- Independent project ownership\n- 60-day manager review template\n- Peer feedback collection\n- 90-day review and goal-setting template\n- Onboarding completion criteria checklist\n- Transition from 'new hire' to 'team member'\n\n**Measurement**\n- New hire satisfaction survey (questions included)\n- Time-to-productivity metrics\n- Manager satisfaction check\n- 6-month and 12-month retention correlation\n\nMake all templates ready to use. Include exact questions, not just topics.",
    "category": "HR & People Management"
  },
  {
    "title": "Performance Review System Builder",
    "description": "Get a complete performance review framework with self-assessment templates, manager evaluation forms, and calibration guidelines.",
    "method": "Paste into any LLM with your company details. Use the output to build or improve your review process.",
    "prompt": "You are an HR strategy consultant who has designed performance management systems for companies ranging from 20 to 20,000 employees.\n\nCompany size: [NUMBER OF EMPLOYEES]\nReview frequency: [ANNUAL/SEMI-ANNUAL/QUARTERLY]\nCurrent challenges: [WHAT'S NOT WORKING WITH CURRENT REVIEWS]\nCompany values: [LIST 3-5 VALUES]\nIndustry: [YOUR INDUSTRY]\n\nDesign a complete performance review system:\n\n**1. Review Framework**\n- Rating scale design (recommend a scale and defend why)\n- Performance dimensions (results vs behaviors vs growth)\n- Weighting between dimensions\n- How to handle different role types (IC vs manager vs exec)\n\n**2. Self-Assessment Template**\n- 8-10 reflection questions that produce useful answers\n- Achievement documentation format\n- Growth areas identification (without making it feel punitive)\n- Career aspiration section\n\n**3. Manager Assessment Template**\n- Rating criteria with behavioral anchors for each level\n- Strength identification framework\n- Development area framing (constructive, specific, actionable)\n- Potential assessment (ready now, ready in 1-2 years, growth in role)\n\n**4. Peer Feedback Collection**\n- 5 peer feedback questions (structured, not open-ended rambling)\n- How to select reviewers fairly\n- Anonymity guidelines\n- How to synthesize peer input\n\n**5. Calibration Process**\n- Manager calibration session structure\n- Rating distribution guidelines (forced curve vs flexible)\n- Bias identification checklist\n- Edge case decision framework\n\n**6. Review Conversation Guide**\n- Meeting structure (time allocation per section)\n- Opening and closing scripts\n- How to deliver tough feedback\n- How to discuss compensation (or separate it)\n- Goal-setting for next period\n\n**7. Compensation Integration**\n- How to tie reviews to raises/bonuses\n- Merit matrix design\n- Communication templates for different outcomes\n\nInclude all templates, scripts, and forms ready to implement.",
    "category": "HR & People Management"
  },
  {
    "title": "Employee Retention Strategy Builder",
    "description": "Share your turnover data and team context to get a data-driven retention strategy with specific interventions for each risk level.",
    "method": "Paste into any LLM with your team details. Implement the highest-impact recommendations first.",
    "prompt": "You are an organizational psychologist specializing in employee retention. You've helped companies cut unwanted attrition by 40%+.\n\nCompany/team size: [SIZE]\nIndustry: [INDUSTRY]\nCurrent annual turnover rate: [PERCENTAGE OR 'DON'T KNOW']\nRoles with highest turnover: [WHICH ROLES LEAVE MOST]\nTop reasons people leave (if known): [EXIT INTERVIEW THEMES]\nAverage tenure: [MONTHS/YEARS]\n\nBuild a comprehensive retention strategy:\n\n**1. Diagnostic Framework**\n- Flight risk assessment criteria (how to identify who might leave)\n- Stay interview question template (10 questions, quarterly cadence)\n- Engagement pulse survey (15 questions, monthly)\n- Exit interview redesign (questions that get honest answers)\n\n**2. Compensation & Benefits Audit**\n- Market rate comparison methodology\n- Total compensation communication strategy\n- Non-monetary benefits that actually move the needle\n- Equity/bonus structure recommendations by level\n\n**3. Career Development System**\n- Career ladder/framework design\n- Individual development plan template\n- Skill-building budget and policy\n- Internal mobility program\n- Mentorship matching criteria\n\n**4. Manager Effectiveness**\n- Manager training priorities (the #1 retention lever)\n- 1:1 meeting structure that builds trust\n- Recognition program design\n- Feedback frequency and quality standards\n\n**5. Culture & Environment**\n- Belonging indicators to track\n- Team ritual recommendations\n- Flexibility policies that retain without losing productivity\n- Burnout prevention system\n\n**6. Targeted Interventions by Risk Level**\n- Green (low risk): maintenance actions\n- Yellow (moderate risk): proactive engagement plan\n- Red (high risk): immediate intervention playbook\n- Already resigned: counteroffer decision framework\n\n**7. Metrics Dashboard**\n- Leading indicators (predict turnover before it happens)\n- Lagging indicators (measure what already happened)\n- Benchmark targets by industry\n- ROI calculation for retention investments\n\nBe specific with dollar figures, timelines, and measurable outcomes.",
    "category": "HR & People Management"
  },
  {
    "title": "Employer Brand Content Strategy",
    "description": "Get a complete employer branding playbook with content pillars, social media strategy, and employee advocacy program design.",
    "method": "Paste into any LLM with your company details. Use the output to attract better candidates through content.",
    "prompt": "You are an employer branding strategist who has helped companies become 'best places to work' and cut recruiting costs by 50%.\n\nCompany: [COMPANY NAME]\nIndustry: [INDUSTRY]\nTeam size: [SIZE]\nHiring needs: [ROLES YOU'RE RECRUITING FOR]\nCurrent employer brand perception: [STRONG/WEAK/UNKNOWN]\nGlassdoor rating: [IF KNOWN]\n\nBuild a complete employer brand strategy:\n\n**1. Employee Value Proposition (EVP)**\n- Define your EVP in one sentence\n- 4-5 EVP pillars with proof points\n- How it differentiates from competitors' EVPs\n- Messaging framework for different audiences (engineers vs marketers vs execs)\n\n**2. Content Pillars (6 themes)**\n- Day-in-the-life content\n- Growth and learning stories\n- Culture and team moments\n- Impact and mission content\n- Behind-the-scenes / how we build\n- Employee spotlights\n\n**3. Channel Strategy**\n- LinkedIn company page: posting cadence, content types, engagement tactics\n- Instagram/TikTok: visual culture content, formats that work\n- Glassdoor: response templates, review encouragement\n- Careers page: must-have sections, copy guidelines\n- Job description brand integration\n\n**4. Employee Advocacy Program**\n- How to recruit internal advocates\n- Content sharing guidelines and templates\n- Incentive structure\n- Training for employees on personal branding\n- Compliance guardrails\n\n**5. Content Calendar**\n- 30-day content calendar with specific post ideas\n- Content batch production workflow\n- User-generated content collection system\n- Event-based content opportunities\n\n**6. Measurement**\n- Application quality metrics\n- Source-of-hire tracking\n- Employer brand awareness surveys\n- Social media engagement benchmarks\n- Cost-per-hire impact\n\nProvide specific copy examples and templates throughout.",
    "category": "HR & People Management"
  },

// ==================== REAL ESTATE ====================

  {
    "title": "Real Estate Listing Description Writer",
    "description": "Enter property details and get a compelling MLS listing description that highlights key features and drives showings.",
    "method": "Paste into any LLM with your property details. Use the output on MLS, Zillow, Realtor.com, and social media.",
    "prompt": "You are a luxury real estate copywriter whose listings sell 20% faster than market average because of how you write descriptions.\n\nProperty type: [SINGLE FAMILY/CONDO/TOWNHOUSE/MULTI-FAMILY/LAND]\nBedrooms/bathrooms: [X BED / X BATH]\nSquare footage: [SQ FT]\nLot size: [IF APPLICABLE]\nYear built: [YEAR]\nLocation: [NEIGHBORHOOD, CITY, STATE]\nPrice: [LISTING PRICE]\nTop 5 features: [LIST THEM]\nRecent upgrades: [ANY RENOVATIONS]\nNearest amenities: [SCHOOLS, PARKS, SHOPPING, TRANSIT]\n\nWrite the following:\n\n**1. MLS Description (250 words max)**\n- Opening hook that creates an emotional picture\n- Key features woven into a narrative (not a bullet list)\n- Neighborhood and lifestyle selling points\n- Close with urgency without being pushy\n- SEO keywords naturally integrated\n\n**2. Social Media Versions**\n- Instagram caption (engaging, emoji-appropriate, with hashtags)\n- Facebook post (longer, community-focused)\n- LinkedIn post (investment angle)\n\n**3. Email Blast Copy**\n- Subject line (3 options)\n- Preview text\n- Body copy with clear CTA to schedule showing\n\n**4. Feature Sheet Headlines**\n- 5 headline options for printed materials\n- 3-line elevator pitch for open houses\n\n**5. SEO-Optimized Blog Snippet**\n- 150-word description for the brokerage website\n- Meta title and description\n- Target keywords\n\nRules: No cliches ('nestled', 'boasts', 'sun-drenched' unless actually true). Be specific over generic. Sell the lifestyle, not just the house.",
    "category": "Real Estate"
  },
  {
    "title": "Real Estate Investment Analyzer",
    "description": "Input property numbers and get a complete investment analysis with cash flow projections, cap rate, ROI, and risk assessment.",
    "method": "Paste into any LLM with your property financials. Get back a comprehensive investment analysis.",
    "prompt": "You are a real estate investment analyst who has underwritten over $500M in residential and commercial deals.\n\nProperty address/description: [PROPERTY]\nPurchase price: [PRICE]\nDown payment: [AMOUNT OR PERCENTAGE]\nInterest rate: [RATE]\nLoan term: [YEARS]\nMonthly rent (expected): [RENT]\nProperty taxes (annual): [TAXES]\nInsurance (annual): [INSURANCE]\nHOA/condo fees: [IF APPLICABLE]\nExpected repairs/capex: [ESTIMATE]\nProperty management: [SELF-MANAGED OR % FEE]\nVacancy assumption: [PERCENTAGE]\n\nDeliver a complete investment analysis:\n\n**1. Cash Flow Analysis**\n- Monthly income breakdown\n- Monthly expense breakdown (PITI + all operating expenses)\n- Net operating income (NOI)\n- Monthly cash flow after debt service\n- Annual cash flow\n- Cash-on-cash return\n\n**2. Return Metrics**\n- Cap rate\n- Cash-on-cash return\n- Gross rent multiplier\n- Debt service coverage ratio (DSCR)\n- Break-even occupancy rate\n\n**3. 5-Year Projection**\n- Year-by-year cash flow (assuming 3% rent growth, 2% expense growth)\n- Equity buildup from mortgage paydown\n- Appreciation scenarios (conservative 3%, moderate 5%, optimistic 7%)\n- Total return including all sources (cash flow + equity + appreciation)\n\n**4. BRRRR Analysis (if applicable)**\n- After-repair value estimate\n- Refinance potential\n- Cash recaptured after refi\n- Infinite return scenario viability\n\n**5. Risk Assessment**\n- Stress test: what if rent drops 10%, 20%?\n- Stress test: what if vacancy doubles?\n- Stress test: what if rates rise at refi?\n- Major capex timeline (roof, HVAC, etc.)\n- Market risk factors\n\n**6. Verdict**\n- Buy / pass / negotiate recommendation\n- What price would make this a strong deal\n- Comparable properties to look at\n\nShow all math. No hand-waving.",
    "category": "Real Estate"
  },
  {
    "title": "Open House Strategy & Script",
    "description": "Get a complete open house playbook with pre-event marketing, day-of scripts, follow-up sequences, and lead capture strategies.",
    "method": "Fill in property details and paste into any LLM. Use the output as your open house execution plan.",
    "prompt": "You are a top-producing real estate agent who converts 30% of open house visitors into qualified leads (vs the 5% industry average).\n\nProperty: [ADDRESS AND BRIEF DESCRIPTION]\nPrice: [LISTING PRICE]\nTarget buyer profile: [FIRST-TIME/MOVE-UP/DOWNSIZER/INVESTOR]\nOpen house date: [DATE AND TIME]\nNeighborhood highlights: [KEY SELLING POINTS]\n\nCreate a complete open house playbook:\n\n**1. Pre-Event Marketing (7-day plan)**\n- Social media posts (3 posts with exact copy, hashtags, and posting schedule)\n- Email blast to database (subject line, body, CTA)\n- Neighborhood door-knock script\n- Broker outreach message\n- Online listing enhancement for the event\n- Signage strategy (how many signs, where to place)\n\n**2. Property Preparation**\n- Staging checklist (room by room)\n- Sensory staging (scent, music, lighting, temperature)\n- Information materials to prepare\n- Tech setup (digital sign-in, virtual tour running)\n\n**3. Day-Of Scripts**\n- Greeting script at the door (first 30 seconds)\n- Guided tour talking points (room by room)\n- Questions to qualify buyers naturally (without interrogating)\n- How to handle: 'just looking' browsers\n- How to handle: serious buyers\n- How to handle: nosy neighbors\n- How to handle: other agents' buyers\n- Closing script to capture contact info\n\n**4. Lead Capture System**\n- Digital sign-in form fields\n- Qualifying questions to include\n- How to get phone numbers (not just emails)\n- Incentive for providing contact info\n\n**5. Follow-Up Sequence (post open house)**\n- Same-day text message template\n- Day 2 email with additional property info\n- Day 4 call script\n- Day 7 'similar properties' email\n- Day 14 market update touchpoint\n- Long-term nurture strategy for not-ready buyers\n\n**6. Metrics to Track**\n- Attendance vs marketing spend\n- Lead quality scoring\n- Conversion to showing/offer\n- What to improve for next open house",
    "category": "Real Estate"
  },
  {
    "title": "Rental Property Management System",
    "description": "Get a complete property management playbook with tenant screening criteria, lease templates, maintenance workflows, and rent collection systems.",
    "method": "Paste into any LLM with your property details. Use the output to systematize your rental management.",
    "prompt": "You are a property management expert who manages 500+ units with a 98% occupancy rate and minimal legal issues.\n\nNumber of units: [HOW MANY RENTALS YOU MANAGE]\nProperty types: [SINGLE FAMILY/MULTI-FAMILY/CONDO]\nLocation: [CITY/STATE]\nSelf-managed or PM company: [WHICH]\nBiggest challenge: [WHAT'S CAUSING YOU PAIN]\n\nBuild a complete property management system:\n\n**1. Tenant Screening Process**\n- Application requirements checklist\n- Screening criteria (income ratios, credit score thresholds, rental history)\n- Red flags to watch for\n- Fair Housing compliance checklist\n- Rejection letter template (legally safe)\n- Approval and next steps communication\n\n**2. Lease Agreement Essentials**\n- Key clauses every lease must have\n- Pet policy structure\n- Late payment policy and fee schedule\n- Maintenance responsibility matrix (landlord vs tenant)\n- Lease renewal process and timeline\n- Move-in/move-out inspection checklist\n\n**3. Rent Collection System**\n- Payment methods to offer\n- Due dates and grace period policy\n- Late fee escalation schedule\n- Partial payment policy\n- Non-payment action timeline (notice to pay, eviction filing)\n- Communication templates for each stage\n\n**4. Maintenance Management**\n- Emergency vs non-emergency classification\n- Response time standards\n- Vendor selection and management\n- Preventive maintenance calendar (monthly, quarterly, annual)\n- Tenant maintenance request workflow\n- Cost tracking system\n\n**5. Financial Tracking**\n- Monthly income/expense tracking template\n- Reserve fund guidelines (per unit)\n- Tax deduction checklist for rental properties\n- Annual budget template\n- Rent increase analysis framework\n\n**6. Tenant Communication Templates**\n- Welcome packet contents\n- Rent increase notice\n- Lease violation notice\n- Maintenance scheduling messages\n- Lease renewal offer\n- Move-out instructions and deposit return\n\nMake everything legally aware (note where state-specific laws apply).",
    "category": "Real Estate"
  },

// ==================== BRANDING & IDENTITY ====================

  {
    "title": "Brand Voice & Tone Builder",
    "description": "Define your brand personality and get a complete voice guide with do's and don'ts, vocabulary lists, and example copy for every channel.",
    "method": "Paste into any LLM with your brand details. Share the output with your entire team as a writing reference.",
    "prompt": "You are a brand strategist who has defined the voice for brands like Mailchimp, Slack, and Nike. You understand that brand voice is strategy, not decoration.\n\nBrand name: [BRAND]\nIndustry: [INDUSTRY]\nTarget audience: [WHO THEY ARE, AGE, SOPHISTICATION LEVEL]\nWhat you sell: [PRODUCT/SERVICE]\nBrand personality (pick 3-5 adjectives): [e.g., BOLD, WARM, WITTY, EXPERT, REBELLIOUS]\nCompetitors to sound DIFFERENT from: [2-3 COMPETITORS]\n\nBuild a complete brand voice guide:\n\n**1. Voice Definition**\n- Brand voice statement (one paragraph)\n- Voice attributes matrix: for each adjective, define what it means, what it sounds like, and what it does NOT sound like\n- Brand archetype identification with rationale\n\n**2. Tone Spectrum**\n- How tone shifts by context (not voice, but tone):\n  - Marketing/promotional: [tone + example]\n  - Educational/help content: [tone + example]\n  - Social media/casual: [tone + example]\n  - Error/apology messages: [tone + example]\n  - Legal/formal: [tone + example]\n  - Sales/persuasion: [tone + example]\n\n**3. Vocabulary Guide**\n- 20 words we ALWAYS use (with context)\n- 20 words we NEVER use (with why)\n- Industry jargon policy (when to use, when to translate)\n- Emoji and punctuation rules\n- Capitalization conventions\n\n**4. Writing Principles**\n- Sentence length and structure preferences\n- Active vs passive voice rules\n- Humor guidelines (what's fair game, what's off-limits)\n- Inclusivity language standards\n- How to handle competitor mentions\n\n**5. Channel-Specific Examples**\n- Write 3 sample social media posts in this voice\n- Write a sample email subject line + preview + opening paragraph\n- Write a sample error message\n- Write a sample product description\n- Write a sample 'About Us' paragraph\n- Write a sample customer support response\n\n**6. Quick Reference Card**\n- One-page cheat sheet a new writer can reference\n- 'We are / We are not' table\n- 3 'before and after' rewrites showing generic copy transformed into brand voice\n\nMake it specific enough that anyone can write on-brand after reading this.",
    "category": "Branding & Identity"
  },
  {
    "title": "Brand Positioning Statement Generator",
    "description": "Answer key questions about your market and get a positioning statement, competitive differentiation map, and messaging hierarchy.",
    "method": "Fill in the market details and paste into any LLM. Use the output as the foundation for all marketing.",
    "prompt": "You are a positioning strategist trained in the methodologies of Ries & Trout, April Dunford, and Byron Sharp.\n\nBrand: [BRAND NAME]\nCategory: [WHAT CATEGORY DO YOU COMPETE IN]\nTarget customer: [SPECIFIC CUSTOMER PROFILE]\nTop 3 competitors: [COMPETITOR NAMES]\nWhat makes you different: [YOUR HYPOTHESIS - BE HONEST]\nWhat customers currently say about you: [IF KNOWN]\n\nBuild a complete positioning strategy:\n\n**1. Category Analysis**\n- Define the category you compete in (and consider redefining it)\n- Category conventions (what everyone does/says)\n- Category tensions (what customers hate about current options)\n- Whitespace opportunities\n\n**2. Competitive Positioning Map**\n- Identify 2 key axes that matter to buyers\n- Plot yourself and competitors on the map\n- Identify the unoccupied position\n- Defend why that position is valuable and ownable\n\n**3. Positioning Statement**\n- Classic format: For [target], [brand] is the [category] that [key benefit] because [reason to believe]\n- Alternative format: Unlike [competitors], we [differentiator]\n- One-sentence version for internal alignment\n- One-paragraph version for external communications\n\n**4. Messaging Hierarchy**\n- Brand promise (one sentence)\n- 3 supporting pillars with proof points\n- Key messages per audience segment\n- Elevator pitch (30 seconds)\n- Boilerplate (for press releases, bios)\n\n**5. Proof Points**\n- Claims you can make with evidence\n- Claims you need to earn\n- Social proof to gather\n- Third-party validation opportunities\n\n**6. Positioning Stress Test**\n- Is it differentiated? (would a competitor say the same thing?)\n- Is it relevant? (do customers actually care?)\n- Is it credible? (can you deliver on this?)\n- Is it sustainable? (can competitors copy this easily?)\n\nBe opinionated. Tell me if my current positioning is weak and why.",
    "category": "Branding & Identity"
  },
  {
    "title": "Complete Brand Identity Brief",
    "description": "Get a comprehensive brand identity brief covering name exploration, visual direction, typography, color psychology, and design system specs.",
    "method": "Paste into any LLM. Use the output as a brief for your designer or branding agency.",
    "prompt": "You are a creative director at a boutique branding agency. You've built brand identities from scratch for over 200 companies.\n\nBusiness: [WHAT THE BUSINESS DOES]\nTarget market: [WHO YOU SERVE]\nBrand personality: [3-5 ADJECTIVE DESCRIPTORS]\nCompetitor brands to differentiate from: [2-3 NAMES]\nAny existing brand elements to keep: [LOGO, COLORS, OR 'STARTING FRESH']\nBudget context: [STARTUP/SMB/ENTERPRISE]\n\nCreate a complete brand identity brief:\n\n**1. Brand Name Exploration (if needed)**\n- 10 name concepts across different naming strategies:\n  - Descriptive (says what you do)\n  - Abstract (unique invented word)\n  - Metaphorical (evocative of a quality)\n  - Founder/personal\n  - Acronym\n- Domain availability check approach\n- Trademark screening notes\n\n**2. Visual Identity Direction**\n- 3 distinct mood board descriptions (different visual directions)\n  - Direction A: [describe aesthetic, references, feeling]\n  - Direction B: [describe aesthetic, references, feeling]\n  - Direction C: [describe aesthetic, references, feeling]\n- Recommend one direction with rationale\n\n**3. Color System**\n- Primary color with hex, RGB, CMYK (with color psychology justification)\n- Secondary color palette (3-4 colors with codes)\n- Neutral palette (backgrounds, text)\n- Accent/action color\n- Color usage ratios (60-30-10 rule application)\n- Accessibility contrast check guidance\n\n**4. Typography System**\n- Heading font recommendation (with Google Fonts or Adobe alternatives)\n- Body text font recommendation\n- Accent/display font if needed\n- Type scale (sizes for H1 through body text)\n- Font pairing rationale\n\n**5. Logo Direction**\n- Logo concept descriptions (3 directions)\n- Logo usage rules (minimum size, clear space, backgrounds)\n- Logo variations needed (full, icon, monochrome, reversed)\n- Favicon and app icon specifications\n\n**6. Brand Applications Preview**\n- Business card layout description\n- Email signature format\n- Social media profile/cover image direction\n- Presentation template direction\n- Website header and hero treatment\n\n**7. Brand Guidelines Table of Contents**\n- Outline what the final brand guidelines document should contain\n- File deliverables checklist\n\nMake this specific enough to hand to a designer as a working brief.",
    "category": "Branding & Identity"
  },

// ==================== E-COMMERCE ====================

  {
    "title": "Shopify Store Launch Checklist",
    "description": "Get a complete pre-launch checklist for your Shopify store covering product setup, payments, shipping, SEO, and go-live preparations.",
    "method": "Paste into any LLM with your store details. Work through the checklist before launching.",
    "prompt": "You are a Shopify expert who has launched 200+ successful stores. You know every setting, app, and optimization that matters.\n\nStore name: [STORE NAME]\nProducts: [WHAT YOU SELL - PHYSICAL/DIGITAL]\nNumber of products: [HOW MANY AT LAUNCH]\nTarget market: [COUNTRY/COUNTRIES]\nPrice range: [LOW/MID/HIGH-END]\nShipping model: [SELF-FULFILLED/DROPSHIP/3PL]\n\nCreate a comprehensive launch checklist:\n\n**1. Store Foundation**\n- Theme selection criteria and top 3 recommendations\n- Essential pages to create (with content guidelines for each)\n- Navigation structure\n- Domain and email setup\n- Legal pages (privacy, terms, refund policy) - what each must include\n\n**2. Product Setup**\n- Product title optimization formula\n- Description template (features, benefits, specs)\n- Image requirements (dimensions, count, types of shots)\n- Variant and option organization\n- Collection/category strategy\n- Inventory tracking setup\n- SEO fields for each product\n\n**3. Payment & Checkout**\n- Payment gateway setup checklist\n- Express checkout configuration (Shop Pay, Apple Pay, Google Pay)\n- Checkout customization priorities\n- Tax configuration by market\n- Currency settings for international\n\n**4. Shipping Configuration**\n- Shipping zone setup\n- Rate strategy (free threshold, flat rate, calculated)\n- Shipping profile configuration\n- Packaging specifications\n- Tracking and notification setup\n\n**5. Essential Apps (10 max)**\n- Email marketing\n- Reviews\n- SEO\n- Analytics\n- Upsell/cross-sell\n- For each: specific app recommendation with free vs paid analysis\n\n**6. Pre-Launch Marketing**\n- 'Coming soon' page setup\n- Email list building pre-launch\n- Social media account setup\n- Launch day promotion plan\n- Influencer seeding strategy\n\n**7. Testing Checklist**\n- Place test order (full flow)\n- Mobile responsiveness check\n- Page speed test\n- Broken link check\n- Email notification review\n- Payment processing verification\n\n**8. Go-Live Day**\n- Hour-by-hour launch day plan\n- Monitoring priorities\n- Common Day 1 issues and fixes\n\nMark each item as [CRITICAL], [IMPORTANT], or [NICE-TO-HAVE].",
    "category": "E-Commerce"
  },
  {
    "title": "Product Description Conversion Machine",
    "description": "Enter product specs and get conversion-optimized descriptions for your store, Amazon, social media, and ads - all from one prompt.",
    "method": "Paste into any LLM with your product details. Get back descriptions for every platform at once.",
    "prompt": "You are a direct-response copywriter who has written product descriptions generating over $50M in e-commerce revenue.\n\nProduct name: [NAME]\nProduct type: [CATEGORY]\nPrice: [PRICE]\nKey features: [LIST 5-7 FEATURES]\nTarget customer: [WHO BUYS THIS AND WHY]\nPain point it solves: [WHAT PROBLEM DOES IT FIX]\nCompetitor products: [WHAT ELSE THEY MIGHT BUY INSTEAD]\n\nWrite conversion-optimized copy for every platform:\n\n**1. Shopify/Website Product Page**\n- Headline (benefit-driven, not feature-driven)\n- Subheadline (specificity and credibility)\n- 5 bullet points (feature > benefit > proof format)\n- Long description (300 words, storytelling approach)\n- Technical specifications table\n- Social proof integration points\n\n**2. Amazon Listing**\n- Title (keyword-optimized, under 200 characters)\n- 5 bullet points (Amazon format: CAPS BENEFIT - supporting detail)\n- A+ Content description sections (3 modules)\n- Backend search terms (250 characters)\n\n**3. Social Media Product Posts**\n- Instagram caption (with hooks, hashtags, CTA)\n- TikTok script (15-second product showcase)\n- Facebook marketplace description\n- Pinterest product pin description\n\n**4. Ad Copy Variations**\n- Facebook/Instagram ad (primary text + headline + description, 3 variations)\n- Google Shopping title and description\n- Google Search ad (3 headlines + 2 descriptions)\n\n**5. Email Copy**\n- Product launch email (subject + body)\n- Product feature spotlight email\n- 'Last chance' urgency email\n\nFor ALL copy: use sensory language, specific numbers over vague claims, address objections within the copy, and include clear CTAs. No fluff words ('amazing', 'incredible', 'revolutionary').",
    "category": "E-Commerce"
  },
  {
    "title": "Cart Abandonment Recovery System",
    "description": "Get a complete cart abandonment recovery system with email sequences, SMS messages, retargeting ad copy, and exit-intent strategies.",
    "method": "Paste into any LLM with your store details. Implement across email, SMS, and ads to recover lost sales.",
    "prompt": "You are an e-commerce retention specialist who recovers 15-25% of abandoned carts (vs the 5-10% industry average).\n\nStore: [STORE NAME AND URL]\nAverage order value: [AOV]\nAverage cart abandonment rate: [IF KNOWN]\nProducts: [WHAT YOU SELL]\nCurrent recovery efforts: [WHAT YOU'RE DOING NOW, OR 'NOTHING']\n\nBuild a complete cart abandonment recovery system:\n\n**1. Exit-Intent Strategy**\n- Pop-up copy (3 variations to test)\n- Discount vs no-discount approach (recommendation based on AOV)\n- Design recommendations\n- Mobile vs desktop treatment\n\n**2. Email Recovery Sequence (4 emails)**\n- Email 1 (1 hour): Reminder - subject line, preview, body, CTA\n- Email 2 (24 hours): Social proof - subject line, preview, body, CTA\n- Email 3 (48 hours): Objection handling - subject line, preview, body, CTA\n- Email 4 (72 hours): Final incentive - subject line, preview, body, CTA\n- For each: exact copy, design layout description, dynamic product block placement\n\n**3. SMS Recovery (2 messages)**\n- SMS 1 (2 hours): Short, personal, with cart link\n- SMS 2 (24 hours): Urgency or incentive\n- Character count, personalization tokens, opt-out compliance\n\n**4. Retargeting Ads**\n- Facebook/Instagram dynamic product ad copy (3 variations)\n- Google Display remarketing ad copy\n- Audience segmentation (by cart value, product type, new vs returning)\n- Frequency cap recommendations\n- Duration of retargeting window\n\n**5. On-Site Recovery**\n- Browser push notification copy\n- Persistent cart reminder bar\n- Wishlist/save-for-later functionality\n- Live chat trigger for high-value carts\n\n**6. Analysis & Optimization**\n- Why people abandon (top 10 reasons with solutions)\n- A/B tests to run (subject lines, incentive amounts, timing)\n- Revenue attribution model\n- Monthly recovery rate targets\n\nInclude all copy ready to deploy. Specify dynamic merge tags.",
    "category": "E-Commerce"
  },

// ==================== PERSONAL DEVELOPMENT ====================

  {
    "title": "Personal Growth Operating System",
    "description": "Design a complete personal development system with goal-setting frameworks, habit trackers, weekly reviews, and accountability structures.",
    "method": "Paste into any LLM with your goals. Get back a personalized system you can implement immediately.",
    "prompt": "You are a performance coach who has helped CEOs, athletes, and creators design systems that compound personal growth over time.\n\nYour current situation: [BRIEF CONTEXT - CAREER, LIFE STAGE]\nTop 3 goals for the next 12 months: [LIST THEM]\nBiggest obstacle: [WHAT KEEPS HOLDING YOU BACK]\nTime available for personal development: [HOURS PER WEEK]\nPreferred tools: [NOTION/OBSIDIAN/PAPER/SPREADSHEET]\n\nDesign a complete Personal Growth Operating System:\n\n**1. Vision & Goal Architecture**\n- 10-year vision statement exercise\n- Annual goal-setting using the 12-week year method\n- Goal hierarchy: vision > annual objectives > quarterly targets > weekly actions\n- For each goal: lead measures vs lag measures\n- Anti-goals: what you're actively saying no to\n\n**2. Daily System**\n- Morning routine design (customized to your schedule)\n- Evening review template (5 questions, under 10 minutes)\n- Energy management framework (when to do deep work, shallow work, rest)\n- Non-negotiable daily habits (maximum 5)\n- Daily scorecard template\n\n**3. Weekly System**\n- Weekly planning ritual (step-by-step, under 30 minutes)\n- Weekly review template (what worked, what didn't, adjustments)\n- Time audit exercise (track actual vs intended time allocation)\n- 'Big 3' weekly outcome identification\n\n**4. Monthly & Quarterly System**\n- Monthly reflection template (10 questions)\n- Quarterly goal review and reset process\n- Life dashboard metrics (health, wealth, relationships, growth)\n- Course correction framework (when to pivot vs persist)\n\n**5. Habit Formation Engine**\n- Habit stacking framework for your specific goals\n- Implementation intentions (if-then plans)\n- Environment design checklist\n- Streak tracking system\n- Failure recovery protocol (miss one, never miss two)\n\n**6. Accountability & Support**\n- Accountability partner framework (who, how often, what format)\n- Progress journaling prompts (weekly)\n- Celebration and reward system\n- Burnout prevention indicators\n\n**7. Learning System**\n- Book/podcast/course selection criteria\n- Note-taking and retention method\n- Application framework (learn > apply > teach)\n- Knowledge management system\n\nMake it practical. No motivational fluff. Just systems that work.",
    "category": "Personal Development"
  },
  {
    "title": "Career Transition Strategy Builder",
    "description": "Describe where you are and where you want to go. Get a complete career transition plan with skill gaps, networking strategy, and timeline.",
    "method": "Paste into any LLM with your career details. Follow the plan step by step.",
    "prompt": "You are a career strategist who has helped 500+ professionals successfully transition into new careers, industries, and roles.\n\nCurrent role: [YOUR CURRENT JOB TITLE AND INDUSTRY]\nYears of experience: [YEARS]\nTarget role: [WHERE YOU WANT TO GO]\nTarget industry: [IF DIFFERENT FROM CURRENT]\nTimeline: [WHEN YOU WANT TO MAKE THE SWITCH]\nConstraints: [FINANCIAL, GEOGRAPHIC, FAMILY, ETC.]\n\nBuild a complete career transition strategy:\n\n**1. Transferable Skills Audit**\n- Map your current skills to target role requirements\n- Identify your top 5 transferable strengths\n- Identify the 3-5 skill gaps you need to close\n- Hidden advantages your background gives you that 'traditional' candidates lack\n\n**2. Gap-Closing Plan**\n- For each skill gap: specific course, certification, or project to close it\n- Free vs paid learning resources (prioritized)\n- Portfolio project ideas that prove competency\n- Timeline for each skill acquisition\n\n**3. Narrative & Positioning**\n- Your career transition story (compelling, not apologetic)\n- How to frame your background as a strength, not a liability\n- LinkedIn headline and summary rewrite\n- Resume positioning strategy (functional vs chronological hybrid)\n- Elevator pitch for networking events\n\n**4. Networking Strategy**\n- 20 types of people to connect with (specific roles, not generic)\n- Warm outreach message templates (LinkedIn, email)\n- Informational interview request script\n- Informational interview question list (15 questions)\n- Follow-up and relationship maintenance system\n- Communities and events to join\n\n**5. Job Search Execution**\n- Where to find opportunities (beyond job boards)\n- Application prioritization framework\n- Cover letter template for career changers\n- Interview preparation for 'why are you switching?' question\n- Salary negotiation approach when changing fields\n\n**6. Risk Mitigation**\n- Financial runway calculation\n- Side project / moonlighting approach\n- Fallback plan if transition is slower than expected\n- Mental health and identity management during transition\n\n**7. 90-Day Action Plan**\n- Week-by-week tasks for the first 3 months\n- Milestones and decision points\n- Metrics to track progress\n\nBe honest about what's realistic. Don't sugarcoat the difficulty.",
    "category": "Personal Development"
  },
  {
    "title": "Burnout Recovery & Prevention Protocol",
    "description": "Assess your burnout level and get a personalized recovery plan with boundary-setting scripts, energy management, and sustainable work habits.",
    "method": "Paste into any LLM. Be honest with the assessment. Use the output as your recovery roadmap.",
    "prompt": "You are a workplace psychologist and burnout specialist who has helped thousands of professionals recover from burnout without quitting their jobs.\n\nYour situation: [DESCRIBE HOW YOU'RE FEELING AND WHAT'S CAUSING IT]\nRole: [YOUR JOB]\nWork hours per week: [HONESTLY]\nHow long you've felt this way: [WEEKS/MONTHS/YEARS]\nWhat you've tried: [ANY PREVIOUS ATTEMPTS TO FIX IT]\n\nBuild a personalized burnout recovery protocol:\n\n**1. Burnout Assessment**\n- Evaluate across the 3 dimensions: exhaustion, cynicism, reduced efficacy\n- Identify your burnout stage (1-5 scale with descriptions)\n- Root cause analysis: is it workload, control, reward, community, fairness, or values mismatch?\n- Urgency assessment: do you need immediate intervention or gradual adjustment?\n\n**2. Immediate Triage (This Week)**\n- 3 things to stop doing immediately\n- 3 boundaries to set this week (with exact scripts)\n- Emergency energy restoration activities\n- Sleep hygiene reset protocol\n- Who to talk to (and what to say)\n\n**3. Boundary-Setting Scripts**\n- How to say no to new projects (5 scripts for different situations)\n- How to push back on unrealistic deadlines\n- How to delegate or renegotiate workload\n- How to set communication boundaries (email, Slack, after-hours)\n- How to have 'the conversation' with your manager\n\n**4. Energy Management System**\n- Energy audit: categorize your tasks as energy-giving vs energy-draining\n- Schedule redesign based on energy patterns\n- Recovery ritual design (micro-breaks, transitions, decompression)\n- Physical energy foundations (movement, nutrition, sleep - specific recommendations)\n\n**5. Sustainable Work Redesign**\n- Job crafting framework (modify tasks, relationships, or perceptions)\n- Meaningful work reconnection exercises\n- Autonomy expansion strategies\n- Progress visibility system (see your impact)\n\n**6. Prevention System (Long-Term)**\n- Weekly burnout check-in (5 questions to monitor yourself)\n- Monthly recalibration ritual\n- Quarterly life audit template\n- Early warning signs specific to you\n- Support system maintenance\n\n**7. Decision Framework**\n- Stay vs go analysis (when burnout means it's time to leave)\n- What to fix before deciding to quit\n- Recovery timeline expectations\n\nNo toxic positivity. No 'just meditate and be grateful'. Real strategies for real burnout.",
    "category": "Personal Development"
  },

// ==================== VIDEO & MULTIMEDIA ====================

  {
    "title": "YouTube Video Script Writer",
    "description": "Enter your video topic and get a complete script with hook, structure, B-roll directions, CTA placement, and retention optimization.",
    "method": "Paste into any LLM with your video topic. Use the output as your filming and editing guide.",
    "prompt": "You are a YouTube content strategist and scriptwriter for channels with 1M+ subscribers. You understand exactly what keeps viewers watching.\n\nChannel niche: [YOUR NICHE]\nVideo topic: [SPECIFIC TOPIC]\nTarget length: [MINUTES]\nTarget audience: [WHO WATCHES YOUR CONTENT]\nVideo style: [TALKING HEAD/TUTORIAL/DOCUMENTARY/VLOG/LIST]\n\nWrite a complete YouTube video script:\n\n**1. Title & Thumbnail Concepts**\n- 5 title options (curiosity gap, number-based, how-to, challenge, contrarian)\n- For each title: thumbnail concept description (text overlay, facial expression, visual element)\n- CTR optimization notes\n\n**2. Hook (First 30 Seconds)**\n- Opening line that stops the scroll (no 'hey guys, welcome back')\n- Pattern interrupt element\n- Promise/preview of what they'll learn\n- 'Stay until the end' teaser (specific, not generic)\n- Timestamp: 0:00 - 0:30\n\n**3. Main Content Script**\n- Section-by-section breakdown with timestamps\n- For each section:\n  - Talking points (conversational, not robotic)\n  - B-roll/visual directions [in brackets]\n  - On-screen text/graphic callouts\n  - Retention hooks between sections ('but here's where it gets interesting...')\n  - Data or examples to include\n- Build to the most valuable point (don't front-load everything)\n\n**4. Engagement Triggers**\n- Where to ask for comments (with specific question)\n- Where to mention subscribe (natural, not begging)\n- Where to reference other videos (end screen setup)\n- Pattern interrupts every 2-3 minutes\n\n**5. Outro & CTA (Final 30 Seconds)**\n- Summary of key takeaways\n- Clear next action for the viewer\n- End screen video recommendation (which video to suggest and why)\n- Final hook for next video\n\n**6. SEO Optimization**\n- Video description template (with links, timestamps, keywords)\n- Tags list (15-20)\n- Hashtags (3-5)\n- Closed caption/subtitle notes\n\n**7. Production Notes**\n- Pacing guidance (when to speed up, slow down)\n- Music mood suggestions per section\n- Jump cut vs continuous shot recommendations\n- Graphics and animation callouts\n\nWrite the script in a conversational tone. Include [VISUAL] and [GRAPHIC] cues throughout.",
    "category": "Video & Multimedia"
  },
  {
    "title": "TikTok & Reels Content Factory",
    "description": "Get 30 days of short-form video ideas with hooks, scripts, trending audio suggestions, and posting strategy for TikTok and Instagram Reels.",
    "method": "Paste into any LLM with your niche. Get back a month of content ready to film.",
    "prompt": "You are a short-form video strategist who has helped creators go from 0 to 100K followers. You understand the TikTok and Reels algorithms intimately.\n\nNiche/industry: [YOUR NICHE]\nTarget audience: [WHO YOU WANT TO REACH]\nGoal: [GROW FOLLOWERS/DRIVE SALES/BUILD BRAND/EDUCATE]\nYour comfort level on camera: [COMFORTABLE/NERVOUS/PREFER NOT TO SHOW FACE]\nProducts or services (if any): [WHAT YOU SELL]\n\nCreate a 30-day short-form content system:\n\n**1. Content Pillars (5 categories)**\n- Educational (teach something valuable)\n- Entertaining (humor, trends, relatability)\n- Inspirational (transformation, results, motivation)\n- Behind-the-scenes (process, daily life, authenticity)\n- Promotional (product/service, soft sell)\n- Ratio recommendation (how often to post each type)\n\n**2. 30 Video Scripts (one per day)**\nFor each video provide:\n- Content pillar it belongs to\n- Hook (first 1-3 seconds - THE most important part)\n- Script/talking points (15-60 seconds)\n- Visual direction (transitions, text overlays, props)\n- Trending audio suggestion or original audio approach\n- CTA (follow, comment, save, share, or link in bio)\n- Hashtag set (5-8 per video)\n- Best posting time recommendation\n\n**3. No-Face Content Ideas (5 options)**\n- Screen recordings with voiceover\n- Text-on-screen storytelling\n- Product/hands-only demonstrations\n- Slideshow/photo montage styles\n- Green screen with content behind you\n\n**4. Trend Adaptation Framework**\n- How to identify trends worth jumping on\n- How to adapt any trend to your niche (3-step formula)\n- When to skip a trend\n- How to start your own trend\n\n**5. Growth Tactics**\n- Posting frequency and time strategy\n- Comment strategy (what to comment on other creators' posts)\n- Collaboration/duet/stitch strategy\n- Hashtag research method\n- How to analyze what's working (which metrics matter)\n\n**6. Batch Production Workflow**\n- How to film 7 videos in 1 hour\n- Equipment essentials (phone setup, lighting, audio)\n- Editing app recommendations and techniques\n- Content recycling strategy (repurpose across platforms)\n\nMake the hooks irresistible. That's what determines everything.",
    "category": "Video & Multimedia"
  },
  {
    "title": "Podcast Launch & Growth Blueprint",
    "description": "Get a complete podcast strategy from concept to launch to growth, including episode structures, guest outreach, and monetization.",
    "method": "Paste into any LLM with your podcast concept. Follow the blueprint from pre-launch through growth phase.",
    "prompt": "You are a podcast strategist who has launched shows that reached top 10 in their category within 90 days.\n\nPodcast concept: [WHAT YOUR SHOW IS ABOUT]\nTarget listener: [WHO IS YOUR IDEAL LISTENER]\nFormat preference: [SOLO/INTERVIEW/CO-HOST/HYBRID]\nEpisode frequency: [WEEKLY/BIWEEKLY]\nGoal: [BUILD AUTHORITY/GENERATE LEADS/MONETIZE/NETWORK]\nBudget: [MINIMAL/MODERATE/PROFESSIONAL]\n\nBuild a complete podcast blueprint:\n\n**1. Show Foundation**\n- Show name options (5 names with reasoning)\n- Podcast description (SEO-optimized for Apple/Spotify)\n- Category and subcategory selection\n- Cover art direction (what works in podcast thumbnails)\n- Intro/outro script (15-20 seconds each)\n- Music and sound design direction\n\n**2. Episode Structure Template**\n- Cold open / teaser (30 seconds)\n- Intro and episode context (1 minute)\n- Main content structure (segments, timing)\n- Mid-roll break points\n- Outro with CTA\n- Total target runtime with reasoning\n\n**3. First 10 Episode Ideas**\n- For each: title, one-sentence description, key talking points\n- Strategic ordering (which episodes first and why)\n- Pillar episodes vs timely episodes\n- 'Gateway' episode for new listeners\n\n**4. Guest Strategy (if interview format)**\n- Ideal guest profile criteria\n- Where to find guests\n- Outreach email template (cold and warm)\n- Pre-interview preparation checklist\n- Interview question framework (not a rigid list - a framework)\n- Post-interview follow-up\n\n**5. Production Workflow**\n- Equipment recommendations by budget tier\n- Recording setup (software, settings, backup)\n- Editing workflow (what to cut, what to keep)\n- Show notes template\n- Publishing checklist\n\n**6. Launch Strategy**\n- Pre-launch runway (4-6 weeks plan)\n- Launch day tactics (release 3-5 episodes at once)\n- Rating and review generation strategy\n- Launch promotion across channels\n\n**7. Growth & Monetization**\n- Week-over-week growth tactics\n- Cross-promotion and podcast swaps\n- Social media content from episodes (clips, quotes, audiograms)\n- Newsletter integration\n- Monetization timeline and options (sponsors, premium content, services)\n- Listener engagement and community building\n\nBe specific with tools, timelines, and tactics. No vague advice.",
    "category": "Video & Multimedia"
  },

// ==================== EXPANDED AI & AUTOMATION ====================

  {
    "title": "AI Workflow Automation Designer",
    "description": "Describe any repetitive business process and get a complete automation blueprint using Zapier, Make, or n8n with step-by-step setup.",
    "method": "Paste into any LLM with the process you want to automate. Get back a complete automation design.",
    "prompt": "You are an automation architect who has designed workflows that save businesses 20+ hours per week using no-code tools.\n\nProcess to automate: [DESCRIBE THE MANUAL PROCESS STEP BY STEP]\nTools currently used: [LIST YOUR CURRENT TOOLS - CRM, EMAIL, SPREADSHEETS, ETC.]\nVolume: [HOW OFTEN THIS PROCESS RUNS - DAILY/WEEKLY/PER CUSTOMER]\nAutomation tool preference: [ZAPIER/MAKE/N8N/NO PREFERENCE]\nBudget for automation tools: [MONTHLY BUDGET]\n\nDesign a complete automation blueprint:\n\n**1. Process Analysis**\n- Map the current manual workflow (visual step-by-step)\n- Identify bottlenecks and error-prone steps\n- Calculate time spent per occurrence\n- ROI projection (time saved x hourly rate x frequency)\n\n**2. Automation Architecture**\n- Trigger event (what kicks off the automation)\n- Action sequence (step by step, what happens automatically)\n- Decision points (if/then logic branches)\n- Data flow diagram (what data moves where)\n- Error handling (what happens when something fails)\n\n**3. Tool-Specific Setup Instructions**\n- Which apps/integrations to connect\n- Step-by-step configuration for each node\n- Field mapping (which data goes where)\n- Filter and formatting rules\n- Testing procedure\n\n**4. Advanced Features**\n- Multi-step workflows with delays\n- Conditional branching logic\n- Lookup tables and data enrichment\n- Webhook integrations for custom apps\n- Scheduled vs triggered execution\n\n**5. Monitoring & Maintenance**\n- Error notification setup\n- Monthly audit checklist\n- Common failure points and fixes\n- Scaling considerations\n- Documentation template for the automation\n\n**6. Phase 2 Enhancements**\n- Additional automations that build on this one\n- AI/LLM integration opportunities\n- Dashboard and reporting automation\n- Team notification and handoff automations\n\nBe specific enough that someone could build this automation in one sitting.",
    "category": "Agentic AI"
  },
  {
    "title": "Custom GPT / AI Assistant Builder",
    "description": "Define your use case and get a complete system prompt, knowledge base strategy, and conversation design for a custom AI assistant.",
    "method": "Paste into any LLM. Use the output to build a Custom GPT, Claude Project, or any AI assistant.",
    "prompt": "You are an AI product designer who has built custom AI assistants used by thousands of people daily.\n\nAssistant purpose: [WHAT SHOULD THIS AI ASSISTANT DO]\nTarget users: [WHO WILL USE IT]\nDomain expertise needed: [WHAT KNOWLEDGE DOMAIN]\nTone: [PROFESSIONAL/CASUAL/TECHNICAL/FRIENDLY]\nPlatform: [CUSTOM GPT/CLAUDE PROJECT/API-BASED/OTHER]\n\nDesign a complete AI assistant:\n\n**1. System Prompt**\n- Write the complete system prompt (this is the most important part)\n- Include: role definition, personality, boundaries, output format\n- Rules for what it should and should not do\n- Edge case handling instructions\n- Conversation style directives\n\n**2. Knowledge Base Strategy**\n- What documents/data to upload\n- How to structure the knowledge for best retrieval\n- Document formatting best practices\n- How to handle information gaps\n- Update and maintenance schedule\n\n**3. Conversation Design**\n- Opening message / greeting\n- 5 conversation starters to suggest\n- Question flow (how it should gather information)\n- Response format templates (for different query types)\n- Follow-up question patterns\n- Handoff protocol (when to escalate to a human)\n\n**4. Guardrails & Safety**\n- Topics to decline (with polite refusal scripts)\n- Hallucination prevention instructions\n- Source citation requirements\n- Confidence expression guidelines\n- Privacy and data handling rules\n\n**5. Testing Scenarios**\n- 10 test prompts covering common use cases\n- 5 edge case prompts to stress test\n- Expected vs unacceptable responses\n- Evaluation criteria\n\n**6. Iteration Plan**\n- How to collect user feedback\n- Common failure patterns to monitor\n- A/B testing approach for prompt variations\n- Version control for system prompt updates\n\nThe system prompt should be production-ready. Write it as if you're shipping it today.",
    "category": "Agentic AI"
  },
  {
    "title": "AI-Powered Content Repurposing Engine",
    "description": "Give it one piece of content (blog, podcast, video) and get a system for turning it into 15+ pieces across every platform.",
    "method": "Paste into any LLM with your original content or a link to it. Get back a complete content multiplication system.",
    "prompt": "You are a content repurposing strategist who helps creators turn one piece of content into a week's worth of multi-platform content.\n\nOriginal content type: [BLOG POST/PODCAST EPISODE/YOUTUBE VIDEO/WEBINAR/NEWSLETTER]\nOriginal content topic: [TOPIC OR PASTE THE CONTENT]\nYour platforms: [LIST ALL PLATFORMS YOU'RE ACTIVE ON]\nBrand voice: [PROFESSIONAL/CASUAL/WITTY/AUTHORITATIVE]\n\nCreate a complete repurposing system:\n\n**1. Content Extraction**\n- Identify the 5-7 key ideas from the original content\n- Pull out quotable one-liners (tweet-worthy)\n- Identify data points and statistics\n- Extract stories and examples\n- Find contrarian or surprising takes\n\n**2. Platform-Specific Transformations**\n\nFrom one piece of content, create:\n\n- **Twitter/X Thread** - 8-10 tweet thread with hook and CTA\n- **LinkedIn Post** - Long-form thought leadership post\n- **LinkedIn Carousel** - 10-slide carousel with text for each slide\n- **Instagram Carousel** - 7-10 slides with design direction\n- **Instagram Reel/TikTok Script** - 30-60 second video script\n- **Email Newsletter** - Subject line + body with personal angle\n- **Blog Post** (if original wasn't a blog) - 800-word SEO article\n- **Podcast Talking Points** (if original wasn't audio) - 10-minute monologue outline\n- **YouTube Short Script** - Under 60 seconds, vertical format\n- **Reddit Post** - Platform-appropriate version (no self-promotion feel)\n- **Quora Answer** - Answer a related question using this content\n- **Pinterest Pin** - Pin title, description, and image direction\n- **Facebook Post** - Community-style, discussion-generating version\n- **Slide Deck** - 5-slide summary for presentations\n- **Infographic** - Visual data representation direction\n\n**3. Publishing Schedule**\n- Day-by-day distribution calendar (which platform, which piece, what time)\n- Staggering strategy (don't post everything at once)\n- Cross-linking between pieces\n\n**4. Repurposing SOP Template**\n- Repeatable process for any future content\n- Time estimate per piece\n- Tools to use for each format\n- Quality checklist before posting\n\nWrite ALL the actual content, not just descriptions of what to write.",
    "category": "Agentic AI"
  },

// ==================== EXPANDED CODING ====================

  {
    "title": "API Design & Documentation Generator",
    "description": "Describe your API requirements and get a complete RESTful API design with endpoints, schemas, authentication, error handling, and OpenAPI spec.",
    "method": "Paste into any LLM with your API requirements. Use the output as your API blueprint and documentation starter.",
    "prompt": "You are a senior backend engineer who has designed APIs serving millions of requests. You follow REST best practices and prioritize developer experience.\n\nProject: [WHAT THE API IS FOR]\nResources/entities: [LIST THE MAIN DATA OBJECTS]\nAuthentication: [API KEY/OAuth2/JWT/NONE]\nExpected scale: [REQUESTS PER DAY]\nConsumers: [INTERNAL/PUBLIC/PARTNER]\n\nDesign a complete API:\n\n**1. Resource Design**\n- For each resource:\n  - Endpoint paths (RESTful naming conventions)\n  - HTTP methods (GET, POST, PUT, PATCH, DELETE)\n  - Request body schemas (with field types, required/optional, validation rules)\n  - Response schemas (success and error)\n  - Query parameters (filtering, sorting, pagination)\n  - Example requests and responses\n\n**2. Authentication & Authorization**\n- Auth flow design\n- Token format and expiration\n- Permission/role model\n- Rate limiting strategy (tiers, headers)\n- API key management\n\n**3. Error Handling**\n- Standard error response format\n- Error code catalog (with HTTP status codes)\n- Validation error format\n- Error messages (developer-friendly)\n\n**4. Pagination & Filtering**\n- Pagination strategy (cursor vs offset)\n- Filtering syntax\n- Sorting parameters\n- Field selection / sparse fieldsets\n\n**5. Versioning Strategy**\n- URL vs header versioning (recommendation)\n- Deprecation policy\n- Migration guides approach\n\n**6. OpenAPI Specification**\n- Generate the OpenAPI 3.0 YAML for the core endpoints\n- Include schemas, examples, and descriptions\n\n**7. Developer Experience**\n- Getting started guide outline\n- SDK recommendations\n- Webhook design (if applicable)\n- Sandbox/testing environment approach\n\nWrite production-quality schemas. No placeholders.",
    "category": "Coding"
  },
  {
    "title": "Code Review Checklist & Standards",
    "description": "Define your tech stack and get a comprehensive code review checklist, PR template, and team coding standards document.",
    "method": "Paste into any LLM with your stack details. Use the output as your team's code review bible.",
    "prompt": "You are a staff engineer who has established code review practices at high-performing engineering teams.\n\nTech stack: [LANGUAGES AND FRAMEWORKS]\nTeam size: [NUMBER OF DEVELOPERS]\nCurrent challenge: [WHAT'S GOING WRONG WITH CODE REVIEWS]\nDeployment frequency: [HOW OFTEN YOU SHIP]\n\nBuild a complete code review system:\n\n**1. Code Review Checklist**\nFor every PR, reviewers should check:\n- Correctness (does it do what it's supposed to?)\n- Security (OWASP top 10, input validation, auth checks)\n- Performance (N+1 queries, memory leaks, unnecessary computation)\n- Readability (naming, structure, comments where needed)\n- Testing (coverage, edge cases, test quality)\n- Error handling (graceful failures, logging, user-facing messages)\n- Architecture (separation of concerns, dependency direction)\n- Accessibility (if frontend)\n- Documentation (API changes, README updates)\n\nFor each item: provide specific things to look for in [YOUR TECH STACK].\n\n**2. PR Template**\n- What changed and why\n- How to test\n- Screenshots (if UI)\n- Checklist for the author\n- Deployment considerations\n- Related tickets/issues\n\n**3. Review Etiquette Guide**\n- How to give feedback (specific, kind, actionable)\n- How to receive feedback (without ego)\n- When to approve vs request changes vs comment\n- Nit vs blocking distinction\n- Response time expectations\n\n**4. Coding Standards**\n- Naming conventions (variables, functions, files, classes)\n- File and folder structure\n- Import ordering\n- Error handling patterns\n- Logging standards\n- Testing conventions (what to test, naming, structure)\n- Git commit message format\n- Branch naming convention\n\n**5. Automation**\n- Linting rules to enforce automatically\n- Pre-commit hooks\n- CI checks that should gate merging\n- Automated code quality metrics\n\nMake it specific to our stack. No generic advice.",
    "category": "Coding"
  },

// ==================== EXPANDED DATA ANALYSIS ====================

  {
    "title": "Data Dashboard Design & KPI Framework",
    "description": "Define your business and get a complete KPI framework with dashboard layouts, metric definitions, and data visualization recommendations.",
    "method": "Paste into any LLM with your business details. Use the output to build dashboards in Looker, Tableau, or Google Sheets.",
    "prompt": "You are a data analytics leader who has built measurement frameworks for companies from seed stage to IPO.\n\nBusiness type: [WHAT YOUR BUSINESS DOES]\nBusiness model: [SAAS/E-COMMERCE/MARKETPLACE/AGENCY/OTHER]\nStage: [STARTUP/GROWTH/MATURE]\nCurrent data tools: [GOOGLE ANALYTICS/MIXPANEL/AMPLITUDE/SPREADSHEETS/ETC]\nBiggest question you can't answer with data right now: [WHAT DO YOU WISH YOU KNEW]\n\nBuild a complete measurement framework:\n\n**1. North Star Metric**\n- Define the one metric that best captures value delivery\n- Why this metric (not revenue, not vanity)\n- How to calculate it\n- Target and benchmark\n\n**2. KPI Hierarchy**\n- Level 1: North Star metric\n- Level 2: 3-5 supporting metrics (input metrics that drive the North Star)\n- Level 3: Team-level operational metrics\n- For each metric: definition, formula, data source, owner, target, frequency\n\n**3. Dashboard Design**\n\nExecutive Dashboard:\n- Layout description (what goes where)\n- 5-7 metrics to display\n- Chart types for each metric\n- Time period and comparison periods\n- Filter options\n\nOperational Dashboard (per department):\n- Marketing metrics and layout\n- Sales metrics and layout\n- Product metrics and layout\n- Finance metrics and layout\n\n**4. Data Visualization Best Practices**\n- Chart type selection guide (when to use line, bar, pie, table, etc.)\n- Color coding system for status (red/yellow/green thresholds)\n- Annotation and context requirements\n- Mobile-friendly design considerations\n\n**5. Reporting Cadence**\n- Daily: what to monitor and alert on\n- Weekly: team review metrics and format\n- Monthly: business review deck template\n- Quarterly: strategic metrics and board reporting\n\n**6. Data Quality**\n- Data validation rules\n- Common data issues to watch for\n- Data dictionary template\n- Metric definition documentation\n\nInclude specific metric formulas and example calculations throughout.",
    "category": "Data Analysis"
  }
